namespace Audio {

    // Put all different types of audio that you need for your game here
    public enum AudioType {
        None,
        ST_01,
        SFX_01,
        SFX_02,
        SFX_Apple_Spawn,
        SFX_Apple_Death,
        SFX_Apple_Attack1,
        SFX_Apple_Attack2,
        SFX_Apple_Attack3,
        SFX_Apple_TakeDamage1,
        SFX_Apple_TakeDamage2,
        SFX_Apple_TakeDamage3,
        SFX_Apple_TakeDamage4,
        SFX_Apple_Walk1,
        SFX_Apple_Walk2,
        SFX_Apple_Walk3,
        SFX_Broccoli,
        SFX_Carrot,
        SFX_Corn,
        SFX_Lettuce,
        SFX_Onion,
        SFX_Potato,
        SFX_Turnip,
        SFX_Wheat,
        Cow_Spawn,
        Cow_Death,
        Cow_Attack1,
        Cow_Attack2,
        Cow_Attack3,
        Cow_TakeDamage1,
        Cow_TakeDamage2,
        Cow_TakeDamage3,
        Cow_Walk1,
        Cow_Walk2
    }
} 